export const CHANGE_ISLOADING = 'CHANGE_ISLOADING';
export const CHANGE_ISLOGIN = 'CHANGE_ISLOGIN';
export const CHANGE_USER = 'CHANGE_USER';

export const ADD_KIT_SUCCESS = 'ADD_KIT_SUCCESS';
export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';